#! /bin/bash

header() {
    cat <<HEADER
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>

<Style id="source">
<IconStyle>
<Icon>
<href>https://raw.githubusercontent.com/mariolpantunes/kmltraceroute/master/icons/flag.png</href>
</Icon>
</IconStyle>
</Style>

<Style id="jump">
<IconStyle>
<Icon>
<href>https://raw.githubusercontent.com/mariolpantunes/kmltraceroute/master/icons/hosting-servers.png</href>
</Icon>
</IconStyle>
</Style>

<Style id="loop">
<IconStyle>
<Icon>
<href>https://raw.githubusercontent.com/mariolpantunes/kmltraceroute/master/icons/backup.png</href>
</Icon>
</IconStyle>
</Style>

<Style id="destination">
<IconStyle>
<Icon>
<href>https://raw.githubusercontent.com/mariolpantunes/kmltraceroute/master/icons/destination.png</href>
</Icon>
</IconStyle>
</Style>

<Style id="lost">
<IconStyle>
<Icon>
<href>https://raw.githubusercontent.com/mariolpantunes/kmltraceroute/master/icons/lost.png</href>
</Icon>
</IconStyle>
</Style>

HEADER
}


get_ip_location() {
    local LONG=""
    local LAT=""
    local C=""
    local IP=$1

    if [ "$IP" = "_" ]; then
        echo "0,0 "
        return 0
    fi
    
    if [ -e GeoIP-override.txt ] ; then
	C="$(grep "^$IP " GeoIP-override.txt | cut -d"#" -f1)"
    fi
   
    if [ -z "$C" ] && [ -e "$cachedir/GeoIP-cache.txt" ] ; then
    C=$(grep -m 1 "^$IP " "$cachedir/GeoIP-cache.txt")
    fi

    if [ "$C" ]; then
	LONG=$(echo "$C" |cut -d" " -f2)
	LAT=$(echo "$C" |cut -d" " -f3)
    echo -e "$LONG,$LAT "
	return 0
    fi
    
    if [ "$DG" = "$IP" ]; then
    url=https://freegeoip.live/json/
    else
    url=https://freegeoip.live/json/$IP
    fi
    
    LOCATION=$(curl -s $url | jq -r '.longitude, .latitude')
    if [ "$LOCATION" ]; then
    read LONG LAT < <(echo $LOCATION)
    echo $IP $LONG $LAT >> "$cachedir/GeoIP-cache.txt"
    echo -e "$LONG,$LAT "
    return 0
    fi
    return 1
}

tracehost() {
    local RES="$1"
    local LONGLATS=""
    local ICON=""
    local IPS=()
    local RTLS=()

    while IFS= read -r line; do
        local IP=$(echo $line | awk '{print $1}')
        IPS+=($IP)
        if [ "$IP" = "_" ]; then 
            RTLS+=("_")
        else
            RTLS+=($(echo $line | awk '{print $2}'))
        fi
    done <<< "$RES"

    # Remove missing RTL
    local END=$(expr ${#RTLS[@]} - 1)
    if [ "${RTLS[0]}" = "_" ]; then
        RTLS[0]=0.0
    fi
    for i in $(seq 1 $END); do
        if [ "${RTLS[$i]}" = "_" ]; then
            RTLS[$i]=${RTLS[(( $i-1 ))]}
        fi
    done

    # Find the min and max RTL
    max=${RTLS[0]}
    min=${RTLS[1]}

    for i in "${RTLS[@]}"; do
        (( $(echo "$i > $max" |bc -l) )) && max=$i
        #(( $(echo "$i < $min" |bc -l) )) && min=$i
    done

    # Define five level color palette for RTL duration
    STEP=$(echo "($max-$min)/5.0" |bc -l)
    THRES1=$(echo "$min + $STEP" |bc -l)
    THRES2=$(echo "$THRES1 + $STEP" |bc -l)
    THRES3=$(echo "$THRES2 + $STEP" |bc -l)
    THRES4=$(echo "$THRES3 + $STEP" |bc -l)

    END=$(expr ${#IPS[@]} - 1)
    local SAMEPLACE=false
    for i in $(seq 0 $END); do
        local IP=${IPS[i]}
        local NEXT_IP=${IPS[((i+1))]}

        if [ $i -eq 0 ]; then
        echo -e "First IP: $IP"
            local C=$(echo $IP | grep -E '^(192\.168|10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.)')
            echo -e "C=$C"
            if [ -z $C ]; then
                echo -e "Not Private IP"
                LONGLAT=$(get_ip_location "$IP")
            else
                echo -e "Private IP"
                LONGLAT=$(get_ip_location "$DG")
            fi
        else
            LONGLAT=$(get_ip_location "$IP")
        fi

        if [ $i -lt $END ]; then
            NEXTLONGLAT=$(get_ip_location "$NEXT_IP")
        fi 

        if [ "$NEXTLONGLAT" = "$LONGLAT" ]; then
            #echo -e "SAME PLACE....."
            SAMEPLACE=true
        else
            ICON="jump"
            if [ "$IP" = "${IPS[0]}" ]; then
                ICON="source"
            fi

            if $SAMEPLACE; then
                ICON="loop"
                SAMEPLACE=false
            fi

            if [ "$LONGLAT" = "0,0 " ]; then
                ICON="lost"
            fi

	        if [ "$i" -eq "$END" ]; then
		        ICON="destination"
	        fi

        cat <<EOF
<Placemark>
<styleUrl>#$ICON</styleUrl> 
<Point><coordinates>$LONGLAT</coordinates></Point>
</Placemark>
EOF

        if [ $i -lt $END ]; then
            RTL=${RTLS[((i+1))]}
            local COLOR="ff3b55ed"
       
            if (( $(echo "$RTL <= $THRES4" |bc -l) )); then
                COLOR="ff5cd5f6"
            fi

            if (( $(echo "$RTL <= $THRES3" |bc -l) )); then
                COLOR="ffa3ae3c"
            fi

            if (( $(echo "$RTL <= $THRES2" |bc -l) )); then
                COLOR="ff9b6320"
            fi

            if (( $(echo "$RTL <= $THRES1" |bc -l) )); then
                COLOR="ff5f3f17"
            fi

            cat <<EOF

<Placemark> 
<LineString>
<coordinates>
$LONGLAT
$NEXTLONGLAT
</coordinates>
</LineString>
<Style> 
<LineStyle>  
<color>#$COLOR</color>
</LineStyle> 
</Style>
</Placemark>

EOF
        fi
    fi
done
}

footer() {
    cat <<FOOTER
</Document>
</kml>
FOOTER
}

# Print the help of traceroute
for i in "$@"; do
    case $i in
    --help)
    traceroute --help
    exit 0
    ;;
    esac
done

cachedir=cache
DG=$(netstat -rn | grep '^\(default\|0\.0\.0\.0\)' | awk '{print $2}')

# Run the traceroute with the parameter defined by the user
RET=$(traceroute -n $@ 2>&1)
RETVAL=$?
# Error, print the error message
if [ $RETVAL -gt 0 ]; then
   echo -e "$RET"
   exit $RETVAL
fi

# Filter the output of the traceroute 
FILTERED=$(echo -e "$RET" | tail -n +2 | awk '{print $2" "$3}' | sed -r 's/\*/_/g')
#echo -e "$FILTERED"

# Output a valid KML
header
tracehost "$FILTERED"
footer
